<template>
  <main class="admin-shell">
    <header><RouterLink to="/">← Woxza</RouterLink><h1>Feature management</h1><p>Manage the live and roadmap capabilities Woxza can discuss on calls.</p></header>
    <section v-if="!token" class="auth-card"><h2>Admin access</h2><input v-model="tokenInput" type="password" placeholder="Admin API token" @keyup.enter="signIn"><button @click="signIn">Continue</button><p v-if="error" class="error">{{ error }}</p></section>
    <template v-else>
      <div class="toolbar"><input v-model="search" placeholder="Search features" @input="load"><select v-model="tag" @change="load"><option value="">All business tags</option><option v-for="item in tags" :key="item">{{ item }}</option></select><label><input v-model="includeInactive" type="checkbox" @change="load"> Show inactive</label><button @click="startCreate">Add feature</button><RouterLink class="button secondary" to="/admin/prompts">Edit prompts</RouterLink></div>
      <p v-if="error" class="error">{{ error }}</p>
      <section v-if="editing" class="feature-form"><div><h2>{{ editing.id ? 'Edit feature' : 'Add feature' }}</h2><button class="plain" @click="cancel">Close</button></div><label>Title<input v-model="editing.title" maxlength="160"></label><label>Description<textarea v-model="editing.description" maxlength="1000"></textarea></label><label>Business tags</label><div class="tag-input"><span v-for="item in editing.businessTags" :key="item">{{ item }} <button @click="removeTag(item)">×</button></span><input v-model="tagDraft" placeholder="Add a tag" @keydown.enter.prevent="addTag"></div><small>Press Enter to create a new tag.</small><div class="form-grid"><label>Priority<input v-model.number="editing.priority" type="number"></label><label>Status<select v-model="editing.status"><option value="live">Live</option><option value="roadmap">Roadmap</option></select></label><label class="check"><input v-model="editing.active" type="checkbox"> Active</label></div><button @click="save">Save feature</button></section>
      <section class="table-wrap"><table><thead><tr><th>Title</th><th>Business tags</th><th>Priority</th><th>Status</th><th>Active</th><th></th></tr></thead><tbody><tr v-for="feature in items" :key="feature.id"><td><strong>{{ feature.title }}</strong><small>{{ feature.description }}</small></td><td><span class="tag" v-for="item in feature.business_tags" :key="item">{{ item }}</span></td><td>{{ feature.priority }}</td><td><span :class="['status', feature.status]">{{ feature.status }}</span></td><td>{{ feature.active ? 'Yes' : 'No' }}</td><td class="actions"><button class="plain" @click="edit(feature)">Edit</button><button class="plain danger" @click="remove(feature, false)">Disable</button><button class="plain danger" @click="remove(feature, true)">Delete</button></td></tr><tr v-if="!items.length"><td colspan="6">No features found.</td></tr></tbody></table></section>
    </template>
  </main>
</template>
<script setup>
import { onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
const localAdminToken = import.meta.env.VITE_LOCAL_ADMIN_MODE === 'true' ? import.meta.env.VITE_LOCAL_ADMIN_TOKEN : ''
const token = ref(localAdminToken || sessionStorage.getItem('woxza_admin_token') || ''), tokenInput = ref(''), items = ref([]), tags = ref([]), tag = ref(''), search = ref(''), includeInactive = ref(false), editing = ref(null), tagDraft = ref(''), error = ref('')
const headers = () => ({ 'content-type':'application/json', authorization:`Bearer ${token.value}` })
async function api(url, options = {}) { const response = await fetch(url, { ...options, headers:{ ...headers(), ...options.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.details?.join(', ') || body.error || 'Request failed'); return body }
async function load() { if (!token.value) return; try { error.value=''; const query = new URLSearchParams({ includeInactive:String(includeInactive.value) }); if (tag.value) query.set('tag', tag.value); if (search.value) query.set('search', search.value); const [features, allTags] = await Promise.all([api(`/api/admin/features?${query}`),api('/api/admin/feature-tags')]); items.value=features.items; tags.value=allTags.items } catch (err) { error.value=err.message } }
function signIn() { token.value=tokenInput.value.trim(); sessionStorage.setItem('woxza_admin_token', token.value); load() }
function startCreate() { editing.value={ title:'', description:'', businessTags:[], priority:100, status:'live', active:true } }
function edit(feature) { editing.value={ id:feature.id, title:feature.title, description:feature.description, businessTags:[...feature.business_tags], priority:feature.priority, status:feature.status, active:feature.active }; tagDraft.value='' }
function cancel() { editing.value=null; tagDraft.value='' }
function addTag() { const value=tagDraft.value.trim().toLowerCase(); if (value && !editing.value.businessTags.includes(value)) editing.value.businessTags.push(value); tagDraft.value='' }
function removeTag(value) { editing.value.businessTags=editing.value.businessTags.filter(tag => tag !== value) }
async function save() { try { error.value=''; const payload={ ...editing.value }; delete payload.id; if (editing.value.id) await api(`/api/admin/features/${editing.value.id}`, { method:'PATCH', body:JSON.stringify(payload) }); else await api('/api/admin/features', { method:'POST', body:JSON.stringify(payload) }); cancel(); await load() } catch (err) { error.value=err.message } }
async function remove(feature, hard) { const action=hard?'permanently delete':'disable'; if (!window.confirm(`Are you sure you want to ${action} “${feature.title}”?`)) return; try { await api(`/api/admin/features/${feature.id}${hard?'?hard=true':''}`, { method:'DELETE' }); await load() } catch (err) { error.value=err.message } }
onMounted(load)
</script>
<style scoped>
.admin-shell{max-width:1180px;margin:0 auto;padding:110px 28px 80px;color:#10213c}.admin-shell header{margin-bottom:30px}.admin-shell h1{font-size:clamp(2rem,5vw,3.5rem);margin:12px 0}.admin-shell p{color:#5e6c80}.auth-card,.feature-form,.table-wrap{border:1px solid #dce3ed;border-radius:16px;background:#fff;padding:24px;box-shadow:0 12px 35px #10213c0b}.auth-card{max-width:460px;display:grid;gap:12px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:20px}.toolbar input,.toolbar select{min-height:42px}.toolbar input:first-child{min-width:230px}.toolbar label{font-size:.9rem}.button,button{border:0;border-radius:8px;padding:11px 15px;background:#2563eb;color:#fff;font:inherit;cursor:pointer;text-decoration:none}.secondary,.plain{background:#edf2f8;color:#162b4c}.danger{color:#b42318}.feature-form{display:grid;gap:12px;margin-bottom:20px}.feature-form>div{display:flex;justify-content:space-between;align-items:center}.feature-form label{display:grid;gap:6px;font-weight:650}.form-grid{display:flex;gap:14px;align-items:end;flex-wrap:wrap}.form-grid label{min-width:150px}.form-grid .check{display:flex;align-items:center;gap:8px;min-height:42px}.feature-form input,.feature-form textarea,.feature-form select,.auth-card input,.tag-input{border:1px solid #cbd5e1;border-radius:8px;padding:10px;font:inherit}.feature-form textarea{min-height:85px;resize:vertical}.tag-input{display:flex;gap:6px;flex-wrap:wrap;padding:6px}.tag-input span,.tag{background:#e7f0ff;color:#174a91;padding:4px 8px;border-radius:999px;font-size:.8rem}.tag-input button{background:none;color:inherit;padding:0 0 0 4px}.tag-input input{border:0;padding:4px;outline:0;min-width:140px}.table-wrap{overflow:auto;padding:0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px;border-bottom:1px solid #e7edf5;vertical-align:top}td small{display:block;color:#64748b;margin-top:4px;max-width:370px}.tag{display:inline-block;margin:2px}.status{font-size:.8rem;font-weight:700;text-transform:capitalize}.status.live{color:#087443}.status.roadmap{color:#9a5c00}.actions{white-space:nowrap}.plain{margin:2px;padding:7px 9px}.error{color:#b42318!important;font-weight:650}@media(max-width:700px){.admin-shell{padding:95px 14px 50px}.actions{min-width:140px}}
</style>
